"use client";

import { Flag } from "lucide-react";
import { COLORS } from "@/lib/design/tokens";
import type { DealRecap } from "@/lib/clients/types";
import { EditableText, EditableStringList, EditableObjectList } from "./editable";
import { patchContent } from "./content-client";
import { Card, CardHeader, PendingCard } from "./ui";

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div style={{ fontSize: 11, fontWeight: 600, color: COLORS.ink3, textTransform: "uppercase", letterSpacing: 0.4, marginBottom: 6 }}>
        {title}
      </div>
      {children}
    </div>
  );
}

export function DealRecapPanel({
  recap,
  clientId,
  onUpdated,
}: {
  recap: DealRecap | null;
  clientId?: string;
  onUpdated?: () => void;
}) {
  if (!recap) {
    return (
      <PendingCard
        icon={Flag}
        title="Deal recap"
        text="Generated by the AI enrichment: how this deal was closed in 3 to 5 key moments, objections, triggers, sales promises and onboarding risks."
      />
    );
  }

  const current = recap;
  async function save(patch: Partial<DealRecap>) {
    if (!clientId) return;
    await patchContent(clientId, "deal_recap", { ...current, ...patch });
    onUpdated?.();
  }

  return (
    <Card id="k-recap" style={{ scrollMarginTop: 64 }}>
      <CardHeader
        icon={Flag}
        title="Deal recap"
        meta={recap.generated_at ? `How this deal was signed · ${new Date(recap.generated_at).toLocaleDateString("en-GB")}` : "How this deal was signed"}
      />
      <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
        <Block title="Deal timeline">
          <EditableObjectList
            items={recap.timeline ?? []}
            schema={[
              { key: "title", label: "Title" },
              { key: "when", label: "When (date or text)" },
              { key: "description", label: "Description", multiline: true },
            ]}
            onSave={(v) => save({ timeline: (v ?? []) as DealRecap["timeline"] })}
            emptyLabel="No key moments"
          />
        </Block>

        <Block title="How the deal was closed">
          <EditableText value={recap.how_closed ?? null} multiline onSave={(v) => save({ how_closed: v ?? undefined })} />
        </Block>

        <div className="ch-grid-2" style={{ gap: 18 }}>
          <Block title="Triggers">
            <EditableStringList items={recap.triggers} onSave={(v) => save({ triggers: v ?? undefined })} emptyLabel="No triggers identified" />
          </Block>
          <Block title="Objections">
            <EditableStringList items={recap.objections} onSave={(v) => save({ objections: v ?? undefined })} emptyLabel="No notable objections" />
          </Block>
          <Block title="Sales promises (to honor)">
            <EditableStringList items={recap.sales_promises} onSave={(v) => save({ sales_promises: v ?? undefined })} emptyLabel="No promises identified" />
          </Block>
          <Block title="Onboarding risks">
            <EditableStringList items={recap.onboarding_risks} onSave={(v) => save({ onboarding_risks: v ?? undefined })} emptyLabel="No risks detected" />
          </Block>
        </div>
      </div>
    </Card>
  );
}
